services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: always

  backend:
    image: campuslife-backend
    env_file:
      - .env
    volumes:
      - ./apps/backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - ${BACKEND_PORT}:3000

  frontend:
    image: campuslife-frontend
    env_file:
      - .env
    volumes:
      - ./apps/frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - ${FRONTEND_PORT}:4200

  postgres:
    image: postgres:16
    user: "${PUID}:${PGID}"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: campuslife
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@campuslife.social
      PGADMIN_DEFAULT_PASSWORD: CampusL1fe
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers.json
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./docker/pgadmin/setup.sh:/pgadmin4/setup.sh:ro
      - pgadmin_data:/var/lib/pgadmin
    entrypoint: ["/bin/sh", "/pgadmin4/setup.sh"]
    ports:
      - 5051:80
    depends_on:
      - postgres
volumes:
  backend_node_modules:
  frontend_node_modules:
  pgadmin_data:
